// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDruCrbUkRESejOimnPU7bTw7hJlFlJTIE',
    appId: '1:790057765201:web:87e76924ed09641d1c6b70',
    messagingSenderId: '790057765201',
    projectId: 'proyecto2-c1be2',
    authDomain: 'proyecto2-c1be2.firebaseapp.com',
    storageBucket: 'proyecto2-c1be2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9I9ZrdI27yC2Onj2VSb5ecFMEE7n6w4g',
    appId: '1:790057765201:android:d85427c248df45141c6b70',
    messagingSenderId: '790057765201',
    projectId: 'proyecto2-c1be2',
    storageBucket: 'proyecto2-c1be2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOlio4GJIwgy3KN7pTXkwUI_4tjFP4MvM',
    appId: '1:790057765201:ios:ab44f70fda43f6471c6b70',
    messagingSenderId: '790057765201',
    projectId: 'proyecto2-c1be2',
    storageBucket: 'proyecto2-c1be2.appspot.com',
    iosClientId: '790057765201-1pj6c0ae4dntipd3ub22rc6hpo2fnmi5.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto219400640',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOlio4GJIwgy3KN7pTXkwUI_4tjFP4MvM',
    appId: '1:790057765201:ios:ab44f70fda43f6471c6b70',
    messagingSenderId: '790057765201',
    projectId: 'proyecto2-c1be2',
    storageBucket: 'proyecto2-c1be2.appspot.com',
    iosClientId: '790057765201-1pj6c0ae4dntipd3ub22rc6hpo2fnmi5.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto219400640',
  );
}
